# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

mlflow:
  run:
    id: 98c4e9e8-562f-4bbb-b255-c6dfd589fc9d
  model:
    name: krateo-mlflow-model-new
    description: "Model registered from MLflow"
  credentials:
    secretRef:
      namespace: mlflow-system
      name: azure-token
      key: access_token