{{- $model := lookup "mlflow.krateo.io/v1alpha1" "Model" .Release.Namespace ( print (include "mlflow-app.fullname" .) "-model" ) }}
{{- if and $model $model.status $model.status.conditions }}
{{- $isReady := false }}
{{- range $condition := $model.status.conditions }}
{{- if and (eq $condition.type "Ready") (eq $condition.status "True") }}
{{- $isReady = true }}
{{- end }}
{{- end }}
{{- if $isReady }}

apiVersion: mlflow.krateo.io/v1alpha1
kind: ModelVersions
metadata:
  name: {{ include "mlflow-app.fullname" . }}-modelversion
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  name: {{ .Values.mlflow.model.name }}
  source: azureml://artifacts/ExperimentRun/dcid.{{ .Values.mlflow.run.id }}/model
  run_id: {{ .Values.mlflow.run.id }}
  description: {{ .Values.mlflow.model.description }}
  authenticationRefs:
    bearerAuthRef: {{ include "mlflow-app.fullname" . }}-mlflow-auth-ref

{{- end }}
{{- end }}